# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1
#matrix:
#  allow_failures:
#    - julia: nightly
sudo: true
notifications:
  email: false
script: julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=false)'
